# Generated by Django 4.2.6 on 2023-11-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_coupon_couponhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='maximum_use',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='minimum_amount',
            field=models.IntegerField(default=60),
        ),
        migrations.DeleteModel(
            name='CouponHistory',
        ),
    ]
