# Generated by Django 4.2.6 on 2023-11-29 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0006_remove_coupon_maximum_use_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payed',
            field=models.BooleanField(default=False),
        ),
    ]
