# Generated by Django 4.2.6 on 2023-12-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0008_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='return_product',
            field=models.BooleanField(default=False),
        ),
    ]
