# Generated by Django 4.2.6 on 2023-12-02 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0009_order_return_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='return_product',
        ),
    ]
