# Generated by Django 4.2.6 on 2023-12-03 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0013_coupon_maximum_use'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='maximum_use',
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkout.coupon'),
        ),
    ]
