# Generated by Django 4.2.6 on 2023-12-04 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0009_alter_userprofile_profile_image'),
        ('checkout', '0014_remove_coupon_maximum_use_order_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userauth.userprofile'),
        ),
    ]
