# Generated by Django 4.2.6 on 2023-12-04 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0009_alter_userprofile_profile_image'),
        ('checkout', '0015_coupon_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='user_profile',
        ),
        migrations.AddField(
            model_name='coupon',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, to='userauth.userprofile'),
        ),
    ]
