# Generated by Django 4.2.6 on 2023-12-23 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0018_wallethistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='order',
            name='razor_pay_id',
        ),
    ]
