# Generated by Django 4.2.6 on 2023-11-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_is_selling_product_selling_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='main_image',
            new_name='image_front',
        ),
        migrations.RenameField(
            model_name='product_image',
            old_name='image_two',
            new_name='extra_image_one',
        ),
        migrations.RenameField(
            model_name='product_image',
            old_name='image_three',
            new_name='extra_image_two',
        ),
        migrations.RenameField(
            model_name='product_image',
            old_name='image_one',
            new_name='image_back',
        ),
        migrations.AddField(
            model_name='product_variant',
            name='sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product_variant',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
