# Generated by Django 4.2.6 on 2023-11-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_main_image_product_image_front_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slug',
            new_name='category_slug',
        ),
        migrations.AddField(
            model_name='category',
            name='category_descripiton',
            field=models.TextField(default=models.CharField(max_length=50, unique=True)),
        ),
    ]
