# Generated by Django 4.2.6 on 2023-11-08 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_slug_category_category_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category_descripiton',
            new_name='category_description',
        ),
    ]
