# Generated by Django 4.2.6 on 2023-12-04 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0014_remove_coupon_maximum_use_order_coupon'),
        ('products', '0009_alter_wishlist_unique_together_alter_wishlist_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checkout.coupon'),
        ),
    ]
