# Generated by Django 4.2.6 on 2023-12-07 12:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0017_alter_coupon_users'),
        ('products', '0010_cart_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checkout.order')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
