# Generated by Django 4.2.6 on 2023-12-08 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_category_offer_categoryoffer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_description',
        ),
    ]
