# Generated by Django 4.2.6 on 2023-12-08 11:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_remove_category_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffer',
            name='expiry_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
