# Generated by Django 4.2.6 on 2023-12-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_category_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffer',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='categoryoffer',
            name='percentage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
