# Generated by Django 4.2.6 on 2023-10-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0002_userprofile_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
