# Generated by Django 4.2.6 on 2023-11-07 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_userprofile_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='profile/dummy_profile.jpg', null=True, upload_to='profile'),
        ),
    ]
