# Generated by Django 4.2.6 on 2023-11-08 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='userprofile/dummy_profile.jpg', null=True, upload_to='userprofile'),
        ),
    ]
