# Generated by Django 4.2.6 on 2023-11-16 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0007_remove_userprofile_email_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_token_created_at',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='otp',
        ),
    ]
