# Generated by Django 4.2.6 on 2023-11-24 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0008_remove_userprofile_email_token_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(default='userprofile/dummy.jpeg', null=True, upload_to='userprofile'),
        ),
    ]
